### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kasia1403** [CJ-MC-Mods/OnlineUUIDMixin#3]
Does this mod clear player's main inventory when a world is saved one day and loaded next day ? If not, so how to disable this ? I would like to play offline and to have my complete inventory all the time, not only planks next day.

**Comment by cjm721** [comment]
No this mod only modifies UUID lookup logic. If you are playing in offline mode you are most likely getting a random UUID every time you log on which breaks what this does.

If you are playing locally should not even have this installed. Its intent is for servers that are behind bungeecord proxy and are using bungecord's (real) authentication instead of relying on individual servers.

**Comment by Kasia1403** [comment]
But do You know maybe which mod causes that my items disappear from my vanilla inventory ( and sometimes also from modded inventories like Aether Legacy slots and Baubles slots ) when I'm opening my world next day ?

**Comment by Kasia1403** [comment]
Could You change this mod's name to one that it will suggest that this mod is for Bungecord ( I don't know even what is Bungecord ).
